/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import BackupRestore.Backup;
import BackupRestore.Restore;
import apoio.GerenciarAuditoria;
import apoio.UsuarioLogado;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author rrs
 */
public class FrmTelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmTelaPrincipal
     */
    public FrmTelaPrincipal() throws FileNotFoundException, IOException {
        initComponents();
        this.setLocationRelativeTo(null);

        //inicializa a auditoria de acordo com seu último estado, lido do properties
        String audState = ga.getSituacao();
        if (audState.equalsIgnoreCase("0")) {
            cbAuditoria.setSelected(true);
            lbAuditoria.setText("LIGADA");
        } else {
            cbAuditoria.setSelected(false);
            lbAuditoria.setText("DESLIGADA");
        }

        lbNomeUsuario.setText(UsuarioLogado.getUsuario().getNome());
    }

    GerenciarAuditoria ga = new GerenciarAuditoria();

    public void defineSituacao() throws FileNotFoundException, IOException {

        //define a situação da auditoria em tempo real
        if (cbAuditoria.isSelected()) {
            ga.setSituacao("0");
            lbAuditoria.setText("LIGADA");
        } else {
            ga.setSituacao("1");
            lbAuditoria.setText("DESLIGADA");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSair = new javax.swing.JButton();
        lbNomeUsuario = new javax.swing.JLabel();
        situacaoAuditoria = new javax.swing.JLabel();
        lbAuditoria = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        situacaoAuditoria1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mNcBAuditoria = new javax.swing.JMenu();
        cbAuditoria = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mItemEnviarEmail = new javax.swing.JMenuItem();
        Ajuda = new javax.swing.JMenu();
        fazerBackup = new javax.swing.JMenuItem();
        fazerRestore = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        situacaoAuditoria.setText("AUDITORIA:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/img.png"))); // NOI18N

        situacaoAuditoria1.setText("USUÁRIO LOGADO:");

        jMenu1.setText("Cadastros");

        jMenuItem1.setText("Usuários");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Equipes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Projetos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Materiais");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        mNcBAuditoria.setText("Auditoria");

        cbAuditoria.setSelected(true);
        cbAuditoria.setText("Ligar/Desligar");
        cbAuditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAuditoriaActionPerformed(evt);
            }
        });
        mNcBAuditoria.add(cbAuditoria);

        jMenuBar1.add(mNcBAuditoria);

        jMenu2.setText("E-mail");

        mItemEnviarEmail.setText("Enviar e-mail");
        mItemEnviarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemEnviarEmailActionPerformed(evt);
            }
        });
        jMenu2.add(mItemEnviarEmail);

        jMenuBar1.add(jMenu2);

        Ajuda.setText("Ajuda");

        fazerBackup.setText("Fazer backup");
        fazerBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fazerBackupActionPerformed(evt);
            }
        });
        Ajuda.add(fazerBackup);

        fazerRestore.setText("Fazer Restore");
        fazerRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fazerRestoreActionPerformed(evt);
            }
        });
        Ajuda.add(fazerRestore);

        jMenuBar1.add(Ajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(situacaoAuditoria)
                    .addComponent(situacaoAuditoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAuditoria, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 444, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(btSair)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(situacaoAuditoria1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbAuditoria, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(situacaoAuditoria))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        UsuariosView dlg = null;
        try {
            dlg = new UsuariosView(this, true);
        } catch (IOException ex) {
            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        dlg.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        DlgEquipesView dlg = null;
        try {
            dlg = new DlgEquipesView(this, rootPaneCheckingEnabled);
        } catch (IOException ex) {
            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        dlg.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        DlgProjetosView dlg = null;
        try {
            dlg = new DlgProjetosView(this, rootPaneCheckingEnabled);
        } catch (IOException ex) {
            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        dlg.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        DlgMateriaisView dlg = null;
        try {
            dlg = new DlgMateriaisView(this, rootPaneCheckingEnabled);
        } catch (IOException ex) {
            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        dlg.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void cbAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAuditoriaActionPerformed
        try {
            defineSituacao();
        } catch (IOException ex) {
            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbAuditoriaActionPerformed

    private void mItemEnviarEmailActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mItemEnviarEmailActionPerformed
    {//GEN-HEADEREND:event_mItemEnviarEmailActionPerformed
        DlgEnviarEmailView dlg = new DlgEnviarEmailView(this, rootPaneCheckingEnabled);
        dlg.setVisible(true);

    }//GEN-LAST:event_mItemEnviarEmailActionPerformed

    private void fazerBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazerBackupActionPerformed

        SimpleDateFormat formatter = new SimpleDateFormat("yyyyMMddHHmmss");
        Date date = new Date(System.currentTimeMillis());

        Backup backup = new Backup();

        try {
            //Runtime.getRuntime().exec("net.exe start spooler ");
            //backup.execCommand("C:/Users/GUSTAVO/Documents/NetBeansProjects/ARQ_ENG/Backup md ARQ_ENG");
            backup.execCommand("C:/Program Files/PostgreSQL/12/bin/pg_dump.exe --host localhost --port 5432 --username postgres --format tar --file C:/Users/GUSTAVO/Documents/NetBeansProjects/ARQ_ENG/Backup/ARQ_ENG" + formatter.format(date) + ".backup arq_eng");
            //backup.execCommand("robocopy C:/Users/GUSTAVO/Documents/NetBeansProjects/ARQ_ENG C:/Users/GUSTAVO/Documents/NetBeansProjects/ARQ_ENG/Backup /E /copyall");
            JOptionPane.showMessageDialog(null, "Backup realizado com sucesso.");
        } catch (IOException ex) {
            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_fazerBackupActionPerformed

    private void fazerRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazerRestoreActionPerformed

        // file = getRestoreFile();file name only
        File file = new File("restore.txt");
        try {
            if (file.createNewFile()) {
                JOptionPane.showMessageDialog(null, "Restore agendado com sucesso, abra o sistema novamente e escolha o arquivo de backup.");
                System.exit(1);
                System.out.println("file.txt File Created in Project root directory");
            } else {
                System.out.println("File file.txt already exists in the project root directory");
            }
        } catch (IOException ex) {
            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

//        JFileChooser seletor = new JFileChooser();
//        seletor.setDialogTitle("Procurar Arquivo");
//        seletor.setFileSelectionMode(JFileChooser.FILES_ONLY);
//        int opcao = seletor.showOpenDialog(this);
//
//        File arquivo = seletor.getSelectedFile();
//
//        Restore restore = new Restore();
//        //quando chamo aqui ele trava o banco, preciso fazer um comando para substituir 
//
//        try {
//            restore.execCommand("C:/Program Files/PostgreSQL/12/bin/pg_ctl -D C:/Program Files/PostgreSQL/12/data stop");
//            restore.execCommand("C:/Program Files/PostgreSQL/12/bin/pg_restore.exe --host localhost --port 5432 --username postgres --dbname arq_eng " + arquivo);
//            restore.execCommand("C:/Program Files/PostgreSQL/12/bin/pg_ctl -D C:/Program Files/PostgreSQL/12/data start");
//            JOptionPane.showMessageDialog(null, "Restore realizado com sucesso.");
//        } catch (IOException ex) {
//            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_fazerRestoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmTelaPrincipal().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ajuda;
    private javax.swing.JButton btSair;
    private javax.swing.JCheckBoxMenuItem cbAuditoria;
    private javax.swing.JMenuItem fazerBackup;
    private javax.swing.JMenuItem fazerRestore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel lbAuditoria;
    private javax.swing.JLabel lbNomeUsuario;
    private javax.swing.JMenuItem mItemEnviarEmail;
    private javax.swing.JMenu mNcBAuditoria;
    private javax.swing.JLabel situacaoAuditoria;
    private javax.swing.JLabel situacaoAuditoria1;
    // End of variables declaration//GEN-END:variables
}
